
fun_app.erl:37:14: The created fun has no local return
fun_app.erl:37:23: Fun application will fail since F :: fun((_,_,_) -> 'ok' | 'true') is not a function of arity 1
fun_app.erl:38:14: The created fun has no local return
fun_app.erl:38:24: Fun application will fail since F :: fun((_,_,_) -> 'ok' | 'true') is not a function of arity 2
fun_app.erl:40:14: The created fun has no local return
fun_app.erl:40:28: Fun application will fail since F :: fun((_,_,_) -> 'ok' | 'true') is not a function of arity 4
