# ERL-1051 - Function already defined

## Example

```erlang
%% foo.erl
-module(foo).
f({_,_}) -> ok.
f(_) -> error.
```

```
$ erlc foo.erl
foo.erl:3:1: function f/1 already defined
%    3| f(_) -> error.
%     | ^
% help: call `erlc -explain ERL-1051` to see a detailed explanation
```

## Explanation

This error is generated by the Erlang linter when a function that is already
defined is defined again with the same name and arity. Sometimes this is
because multiple clauses of the same clauses are not separated by semicolon
`;`. In the example above, the first clause of `f/1` ends with a period `.`.
This tells the linter that the definition of `f/1` has ended. Then the
second clause of `f/1` is treated as a separate function, instead of another
clause.

Another cause of this error is that a function is meant to have the
same name but a different arity than another existing function. This is
allowed because functions with the same name and different arities are
considered different functions. Change the second function's arity to be
different from the first function can fix this error.

To fix this error in general, check spellings and arities so that only
one definition exists for each function. If the second definition of a
function is unwanted, simply remove the extra definition.

For more information about how function definition works, please refer to the 
[Reference manual](`e:system:ref_man_functions`).
